### ISSUE TITLE
ViewOfResultSet.java:38: Fix eo-yaml block scalars rendering

### ISSUE THREAD

**Issue by 0pdd** [rocket-3/dbmss#122]
The puzzle `40-915526f3` from #40 has to be resolved: 

https://github.com/rocket-3/dbmss/blob/117d1db7b2c49d5bbc9e7990abba2be10e1ad4a0/src/main/java/org/fusionsoft/database/snapshot/objects/dbms/ViewOfResultSet.java#L38-L38

The puzzle was created by rocket on 04-Nov-21. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by rocket-3** [comment]
The probjem doesn't actually appears at code, because of some hack at client-side class MultilineScalarEntry, but there's still a bug inside `eo-yaml` library

**Comment by 0pdd** [comment]
The puzzle `40-915526f3` has disappeared from the source code, that's why I closed this issue. //cc @rocket-3
