### ISSUE TITLE
Implement `Snapshot` related thing

### ISSUE THREAD

**Issue by rocket-3** [rocket-3/dbmss#15]

**Comment by 0pdd** [comment]
@rocket-3 17 puzzles [#22](https://github.com/rocket-3/dbmss/issues/22), [#23](https://github.com/rocket-3/dbmss/issues/23), [#24](https://github.com/rocket-3/dbmss/issues/24), [#25](https://github.com/rocket-3/dbmss/issues/25), [#26](https://github.com/rocket-3/dbmss/issues/26), [#27](https://github.com/rocket-3/dbmss/issues/27), [#28](https://github.com/rocket-3/dbmss/issues/28), [#29](https://github.com/rocket-3/dbmss/issues/29), [#30](https://github.com/rocket-3/dbmss/issues/30), [#31](https://github.com/rocket-3/dbmss/issues/31), [#32](https://github.com/rocket-3/dbmss/issues/32), [#33](https://github.com/rocket-3/dbmss/issues/33), [#34](https://github.com/rocket-3/dbmss/issues/34), [#35](https://github.com/rocket-3/dbmss/issues/35), [#36](https://github.com/rocket-3/dbmss/issues/36), [#37](https://github.com/rocket-3/dbmss/issues/37), [#38](https://github.com/rocket-3/dbmss/issues/38) are still not solved.

**Comment by 0pdd** [comment]
@rocket-3 all 17 puzzles are solved here: [#22](https://github.com/rocket-3/dbmss/issues/22), [#23](https://github.com/rocket-3/dbmss/issues/23), [#24](https://github.com/rocket-3/dbmss/issues/24), [#25](https://github.com/rocket-3/dbmss/issues/25), [#26](https://github.com/rocket-3/dbmss/issues/26), [#27](https://github.com/rocket-3/dbmss/issues/27), [#28](https://github.com/rocket-3/dbmss/issues/28), [#29](https://github.com/rocket-3/dbmss/issues/29), [#30](https://github.com/rocket-3/dbmss/issues/30), [#31](https://github.com/rocket-3/dbmss/issues/31), [#32](https://github.com/rocket-3/dbmss/issues/32), [#33](https://github.com/rocket-3/dbmss/issues/33), [#34](https://github.com/rocket-3/dbmss/issues/34), [#35](https://github.com/rocket-3/dbmss/issues/35), [#36](https://github.com/rocket-3/dbmss/issues/36), [#37](https://github.com/rocket-3/dbmss/issues/37), [#38](https://github.com/rocket-3/dbmss/issues/38).
