### ISSUE TITLE
Refactor of `SnapshotCreateProcedure` artefacts .

### ISSUE THREAD

**Issue by rocket-3** [rocket-3/dbmss#39]
Fix the created puzzles and re-arrange them

**Comment by 0pdd** [comment]
@rocket-3 2 puzzles [#51](https://github.com/rocket-3/dbmss/issues/51), [#55](https://github.com/rocket-3/dbmss/issues/55) are still not solved.

**Comment by 0pdd** [comment]
@rocket-3 the puzzle [#55](https://github.com/rocket-3/dbmss/issues/55) is still not solved; solved: [#51](https://github.com/rocket-3/dbmss/issues/51).

**Comment by 0pdd** [comment]
@rocket-3 all 2 puzzles are solved here: [#51](https://github.com/rocket-3/dbmss/issues/51), [#55](https://github.com/rocket-3/dbmss/issues/55).
