### ISSUE TITLE
Remove constants and plain textual objects

### ISSUE THREAD

**Issue by rocket-3** [rocket-3/dbmss#4]
We need to keep the design clean and object-oriented.

These objects are just a labels now, and if we really need such thing, maybe just rename them and have a common parent class, a.e. `Label` for grouping or sorting. 

Or we create such classes like `DbObjectType`  to actually have some related behavior besides just saying a name. 
If it's so, we may keep them and if we want them also to say a name, we can have a `Label` encapsulated for this job.

**Comment by 0pdd** [comment]
@rocket-3 2 puzzles [#10](https://github.com/rocket-3/dbmss/issues/10), [#7](https://github.com/rocket-3/dbmss/issues/7) are still not solved.

**Comment by 0pdd** [comment]
@rocket-3 all 2 puzzles are solved here: [#10](https://github.com/rocket-3/dbmss/issues/10), [#7](https://github.com/rocket-3/dbmss/issues/7).
